### ISSUE TITLE
[TODO] Resolve circular selectors deps

### ISSUE THREAD

**Issue by Amareis** [ppldo/vanillin#5]
Using the "marker" technque + composeStyles.

```css
.one .two {
  color: red;
}

.two > .one {
 color: green;
}
```

```ts
const twoMarker = style({})

export const one = style({
  selectors: {
    [`${twoMarker} > &`] {
      color: green;
    }
  }
})

export const two = composeStyles(twoMarker, style({
  selectors: {
    [`${one}  &`] {
      color: red;
    }
  }
}))
```
